# Generated by Django 6.0.6 on 2026-07-09 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Url',
            new_name='ShortenURL',
        ),
    ]
